image: docker:20-git
services:
  - docker:20-dind


variables:
  COMPOSE_FILE: ./Grafana_Prometheus/docker-compose.yml
  DOCKER_TLS_CERTS: "/certs"

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  variables:
    DOCKER_IMAGE: ubuntu
    DOCKER_TAG: 1.0.0
    
  script:
    - cd python_app
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:DOCKER_TAG .

# test_app:
#   stage: test
#   before_script:
#     - echo "Testing created docker image"
#   script:
#     - sudo docker history $DOCKER_IMAGE:DOCKER_TAG
#     - docker scan $DOCKER_IMAGE:DOCKER_TAG