image: python:3.9-alpine

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  variables:
    DOCKER_IMAGE: ubuntu
    DOCKER_TAG: 1.0.0
    
  script:
    - cd python_app
    - sudo docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - sudo docker build -t $DOCKER_IMAGE:DOCKER_TAG .

# test_app:
#   stage: test
#   before_script:
#     - echo "Testing created docker image"
#   script:
#     - sudo docker history $DOCKER_IMAGE:DOCKER_TAG
#     - docker scan $DOCKER_IMAGE:DOCKER_TAG