workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

image: alpine:3.17.3
variables:
  INSTALL_DOCKER: apk add docker
  DOCKER_IMAGE: python
  DOCKER_TAG: app-1.0


stages:
  - test
  - build
  - deploy

test_env:
  stage: test
  variables:
    RUN_TEST_SCRIPT: test.sh
  before_script:
    - echo "Preparing to run tests"
    - echo "Adding $REQUIREMENTS!"
    - cat $REQUIREMENTS
    - echo "Test started in New branch!"
    - $INSTALL_DOCKER
  script:
    - chmod +x $RUN_TEST_SCRIPT
    - ./$RUN_TEST_SCRIPT

build_app:
  stage: build
  only:
    - main
  before_script:
    - $INSTALL_DOCKER
  script:
    - cd python_app
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push 867452/python:$DOCKER_TAG

deploy_app:
  only:
    - main
  stage: deploy
  needs:
    - build_app
  before_script:
    - echo "Deploying pushed $DOCKER_IMAGE:$DOCKER_TAG from CR"
    - $INSTALL_DOCKER
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  script:
    - docker pull $DOCKER_IMAGE:$DOCKER_TAG .
    - docker images
    - docker run -it $DOCKER_IMAGE:$DOCKER_TAG
    - docker ps