workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

variables:
  #IMAGE_NAME: python
  IMAGE_TAG: app-3.0
  REPO: $CI_REGISTRY_IMAGE/python
  DEV_URL: google.com

stages:
  - test
  - build
  - deploy

unit_test_run:
  stage: test
  image: python:3.11.3-alpine3.16
  tags:
    - local
    - docker
    - linux
  variables:
    UNIT_TEST: unit_tests.py
    UNIT_TEST_RESULT: unittest_result.xml
  before_script:
    - echo "Preparing to run tests"
    - cd python_app
  script:
    - python3 $UNIT_TEST > $UNIT_TEST_RESULT 2>&1
  artifacts:
    when: always
    reports:
      junit: python_app/$UNIT_TEST_RESULT


build_app:
  stage: build
  only:
    - main
  tags:
    - local
    - shell
 # variables:
    #REPO: registry.gitlab.com/kacperblaz/kubernetes_training .
  before_script:
    - cd python_app
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
#    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t $REPO:$IMAGE_TAG .
    - docker push $REPO:$IMAGE_TAG

deploy_app:
  only:
    - main
  stage: deploy
  tags:
    - aws
    - remote
    - shell
    - ubuntu
  needs:
    - build_app
  before_script:
    - echo "Logging to dev-server on aws and deploying python app from CR"
    - chmod 700 $SSH_DEV_KEY
  script:
    - scp -o StrictHostKeyChecking=no -i $SSH_DEV_KEY docker-compose.yml ubuntu@$IP_ADDRESS:/home/ubuntu/
    - ssh -o StrictHostKeyChecking=no -i $SSH_DEV_KEY ubuntu@$IP_ADDRESS "
        ls
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        export DC_IMAGE_NAME=$REPO &&
        export DC_IMAGE_TAG=$IMAGE_TAG &&
        docker-compose down &&
        docker-compose up -d &&
        docker ps"
  environment:
    name: google_platform
    url: $DEV_URL