workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

image: docker:20-git
services:
  - docker:20-dind


stages:
  - test
  - build
  - deploy

test_env:
  stage: test
  variables:
    RUN_TEST_SCRIPT: test.sh
  before_script:
    - echo "Preparing to run tests"
    - echo "Adding $REQUIREMENTS!"
    - cat $REQUIREMENTS
    - echo "Test started in New branch!"
  script:
    - chmod +x $RUN_TEST_SCRIPT
    - ./$RUN_TEST_SCRIPT

build_app:
  stage: build
  only:
    - main
  variables:
    DOCKER_IMAGE: python
    DOCKER_TAG: app-1.0
  script:
    - cd python_app
    - docker login registry.gitlab.com
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push 

deploy_app:
  only:
    - main
  stage: deploy
  needs:
    - build_app
  before_script:
    - echo "Deploying pushed $DOCKER_IMAGE:$DOCKER_TAG from CR"
    - docker login registry.gitlab.com
  script:
    - docker pull $DOCKER_IMAGE:$DOCKER_TAG .
    - docker images
    - docker run -it $DOCKER_IMAGE:$DOCKER_TAG
    - docker ps